### ISSUE TITLE
Cannot use NFS backed mount for container data

### ISSUE THREAD

**Issue by deed02392** [SickGear/SickGear.Docker#11]
Due to the chown operation required to execute the container, it is not possible to use an nfs mount point to store configuration data.

I am using CoreOS with Docker and SickGear and using an NFS mount for the /config mountpoint. Due to no-root-squash option on NFS, which is an essential security mechanism when sharing files with NFS, the root chown operation attempted by this Docker container fails, causing the software to stop.

**Comment by ressu** [comment]
I never thought of that scenario. I think the best way to deal with this situation is to check if the configuration and configuration directory is already owned by the destination user. This still leaves a possibility of having some files misconfigured, but I don't think it's always the best idea to stack up different environment variables.

**Comment by deed02392** [comment]
I agree that's probably the best solution if you insist on implementing permissions logic in the container.

**Comment by deed02392** [comment]
Fixed in PR: #12 

It checks for perms before trying to chown, and also fixes the config.ini ownership issue (you cannot copy a file to an NFS store as root, because root is not allowed to create files on an NFS share unless no_root_squash is on, which it shouldn't be).

**Comment by ressu** [comment]
Very nice. I'll add a few comments to the PR, but looking good.
