### ISSUE TITLE
Sickgear really slow

### ISSUE THREAD

**Issue by thib3113** [SickGear/SickGear.Docker#28]
I've just install Sickgear on docker, and import my database from Sickgear (not in docker) .

And I found, Sickgear is really really slow, like the request never end some times (lot of requests always in "pending" in chrome debugger) ...

It happen, when I try to add a TV show, I've done some tests, and it's re-happen.

The container is alive, but didn't log, and the file are not modified (in config folder, database files are not updated) . 

I've created the container today, so I think I use the latest version of sickgear .

So, I don't know how to help you more :/ .

**Comment by JackDandy** [comment]
@thib3113 probably best you stick with a traditional install for now. as i'm not sure how long it will take for the docker guy to get free time to help.

**Comment by thib3113** [comment]
Yes I understand, but I'm dockerising all my process, to remove the OS, so I can't keep the regular installation .

I've see other SG images, so I'll try them, or using another tool supporting docker :/ .

**Comment by JackDandy** [comment]
yeah try another image, I know that one of them will work for you.

Good luck.

**Comment by thib3113** [comment]
@JackDandy hum, why closing it ?

Yes I can't wait a lot, but the bug is always here ... If it's not for me, I think it's need to be investigued a little (with adding some logs for the issue for example) .

**Comment by JackDandy** [comment]
I closed this as no one else has reported an issue, maybe it is local to your set up, perhaps incorrect docker hub image. Or even possible local docker configuration/network is wrong.
