### ISSUE TITLE
Docker to apply pull rate limiting Nov 2020

### ISSUE THREAD

**Issue by JackDandy** [SickGear/SickGear.Docker#38]
Docker announced Aug 24 2020.
```
... rate limits for container image pulls.

... the following pull rate limits to Docker subscription plans that will take effect November 1, 2020:
  
    * Free plan – anonymous users: 100 pulls per 6 hours 
    * Free plan – authenticated users: 200 pulls per 6 hours
    * Pro plan – unlimited
    * Team plan – unlimited
```
So any docker image will be allowed a **number of users** to pull an update before Docker sends an error that no more can be pulled for 6 hours. 

It is $60 per year for the **Pro plan**. If people can donate, please contact us. However, we cannot take this cost on, therefore, if there is no Docker alternative to host images, then the rate limiting will apply to the Official SickGear docker, and service disruption should be expected as it is out of our control.

**Comment by anoma** [comment]
See
https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/

`Finally, as part of Docker’s commitment to the open source community, before November 1 we will be announcing availability of new open source plans. To apply for an open source plan, please complete the short form here.`

**Comment by JackDandy** [comment]
Yeah, I filled their survey in, dunno, there is nothing at the end apart from a "Thank you". Guess we shall see if it amounts to anything good for users. Hoping it does, but it seems a little vague at this time.

**Comment by JackDandy** [comment]
Just putting a note on this here;

the baked in watchtower support could be removed and the hibernated SG core updater logic reinstated into the main branch. This would enable moving parts inside the master image, however, it would enable users to pull updates directly from GitHub without being affected by Docker server API limits. Indeed, Docker servers would only need to be contacted on initial install instead of for the tasks "check update available" and "perform version update".

The above fallback will remain dormant if the Docker "open source plan" is awarded and users don't have troubles.

**Comment by JackDandy** [comment]
Just putting a note on this here;

the guidance for "Manual updates" and "Auto Watchtower" could be removed and the hibernated SG core updater logic reinstated into the main branch. Of course, this would bring moving parts inside the master image, however, it would enable users to pull updates directly from GitHub without being affected by Docker server API limits. Indeed, Docker servers would only need to be contacted on initial install instead of for the tasks "check update is available" and "perform version update".

The above fallback can remain dormant if the Docker "open source plan" is awarded and users don't experience troubles.

**Comment by herkalurk** [comment]
Just so everyone is aware, you can make a free account at docker and you will be 'authenticated' and get the 200 pulls per 6 hours.  Then it's just a matter of doing the `docker login` on your docker instance.

**Comment by JackDandy** [comment]
Great news docker users...

SickGear Docker has been approved as an open source namespace...

> For the approved, non-commercial, open source namespaces, Docker will suspend data pull rate restrictions, with no egress restrictions applying to any Docker users pulling images from those namespaces

Thank you Docker :-)
