### ISSUE TITLE
Python version in base container is too high...

### ISSUE THREAD

**Issue by herkalurk** [SickGear/SickGear.Docker#40]
I have the latest version of the container and it appears the base container updated to a higher python version than you were expecting.

```
Python 3.8.6 detected.
Sorry, SickGear requires a Python version 2. 7. 9 - 2. 7. 18, 3. 7. 1 - 3. 8. 5
Python 3.8.6 detected.
Sorry, SickGear requires a Python version 2. 7. 9 - 2. 7. 18, 3. 7. 1 - 3. 8. 5
Python 3.8.6 detected.
Sorry, SickGear requires a Python version 2. 7. 9 - 2. 7. 18, 3. 7. 1 - 3. 8. 5
Python 3.8.6 detected.
Sorry, SickGear requires a Python version 2. 7. 9 - 2. 7. 18, 3. 7. 1 - 3. 8. 5
Python 3.8.6 detected.
Sorry, SickGear requires a Python version 2. 7. 9 - 2. 7. 18, 3. 7. 1 - 3. 8. 5
```

**Comment by JackDandy** [comment]
A new build was run 4 hours ago, it accepts 3.8.6, i have just triggered a new build - again. If that doesn't work, I don't know what to do.

**Comment by JackDandy** [comment]
A new build was run 4 hours ago, it accepts 3.8.6, a new build was just `triggered` - again. If that doesn't work, The 3.8 in the dockerfile can be dropped to 3.7.

Please let me know.

**Comment by JackDandy** [comment]
Confirmed 3.8.6. working fine

<img src="https://i.vgy.me/CSopXO.png">
