### ISSUE TITLE
Docker builds back on track

### ISSUE THREAD

**Issue by JackDandy** [SickGear/SickGear.Docker#43]
- The latest releases are being built again, with images pushed to DockerHub.

- New Alpine builds are in effect for both master and develop branches.

- Python 3.9 is now used everywhere.

- Develop has had an overhaul from the old OS to Alpine, I have done this blind so it probably won't even work, feedback would be appreciated on this one.

**Comment by sanchon** [comment]
I'm experiencing a problem since a few days ago, the container fails to start. I'm using the `latest` image.

This is what I see in the container's log (multiple times):
```
The Python module Cheetah is required,
Manually install using...,
cd <sickgear_installed_folder>,
python -m pip install --user -r requirements.txt,
python sickgear.py
```

**Comment by JackDandy** [comment]
@sanchon thanks for reporting.

So I decided to investigate the build mechanics of Docker.  I am not a Linux user, but I found that the original SickGear Docker used a Linux Docker base image which was a fine decision, but someone later persuaded him to switch to Alpine Linux. The persuasion was that age old marketing trick that Alpine images are _small_.  For the `Go` language, Alpine is fine, but for Python, Alpine is bad, really bad! And this wasn't appreciated. 

It turns out that Alpine images can create quite some nasty issues, one was a memory issue that had to be fixed inside SickGear itself, but a hidden issue was that the Docker build time for performance binaries that SickGear uses is 45 minutes because Alpine does not support Pypi system binaries like most other Linux base image do.  This is because Alpine is built with a system that is completely incompatible with all PyPi (and most Linux) builds.  Therefore, every module has to be purpose built for Alpine, and this means adding 45 minutes to every single SickGear release.  Now that DockerHub stopped auto-building for OpenSource, the move to GitHub builder brought all this out into the light for me when no one answered my call for help, and I had to look into this and discover this craptastic mess - so now the SickGear Docker is being ripped apart again.

By testing on the develop branch, I saw the 45 minutes slashed to 3 minutes by using a different image, however, I also found other things too, so I am still undecided on a final direction. 

I think for now i will revert the old master image so that you can at least use that for now. It would be nice if you were in IRC so I could ask you to test the images as I cannot, but no worries if not.

**Comment by JackDandy** [comment]
Build triggered, it should be done in just under an hour. See how awful that is !?!?!

**Comment by JackDandy** [comment]
@sanchon There, built, 60 mins. Should be okay, but do please let me know how it goes.

**Comment by sanchon** [comment]
The new image works great! Thank you very much!

If you want a volunteer to test the `develop` branch you can count on me!

**Comment by JackDandy** [comment]
@sanchon Great! 

So the develop is ready for testing now
