### ISSUE TITLE
latest images not starting

### ISSUE THREAD

**Issue by sanchon** [SickGear/SickGear.Docker#44]
Logs from `latest` image:
```
/entrypoint.sh: line 13: groupmod: not found,
/entrypoint.sh: line 13: groupmod: not found,
/entrypoint.sh: line 13: groupmod: not found,
/entrypoint.sh: line 13: groupmod: not found,
```

Logs from `develop` image:
```
su-exec: python: No such file or directory,
su-exec: python: No such file or directory,
su-exec: python: No such file or directory,
su-exec: python: No such file or directory,
su-exec: python: No such file or directory,
```

**Comment by JackDandy** [comment]
rebuilt, fingers crossed, no need to set a new issue, just reply below.

**Comment by JackDandy** [comment]
@sanchon rebuilt, fingers crossed, no need to set a new issue, just reply below.

**Comment by sanchon** [comment]
reinstalled both images, logs look exactly the same

**Comment by JackDandy** [comment]
that ounds like you are using an old image or something

**Comment by sanchon** [comment]
this is weird...

```
$ docker-compose up -d
Pulling sickgear (sickgear/sickgear:latest)...
latest: Pulling from sickgear/sickgear
a0d0a0d46f8b: Already exists
7107358e2cfd: Pull complete
d07d1553db42: Pull complete
f2df1826249f: Pull complete
Digest: sha256:c66554cb7955cc634768bc073d7acb7fb7704e0fc71d724993aba3b9cee2a2e0
Status: Downloaded newer image for sickgear/sickgear:latest
Recreating sickgear ... done
```

sha256 doesn't match this: DIGEST:sha256:7c2fc4ead1e7e9da92d143a9f93acc806f023db1d64ae3bd344f76ee06a97c26 so I guess dockerhub is caching something... I will try later...

**Comment by JackDandy** [comment]
just pushed another image

**Comment by sanchon** [comment]
`develop` is still writing `/entrypoint.sh: line 13: groupmod: not found` in the container log but `latest` starts just fine now. 

I thought I could use the sha256 digest to check if I really am downloading the latest version, but it seems I cannot, it's a [whole thing...](https://github.com/docker/hub-feedback/issues/1925#issuecomment-565646445) whatever...

**Comment by JackDandy** [comment]
it thought it was a bit confusing your OP, you have `develop` and `latest` mixed around, so when i went to look at the issue, it didn't make sense until i swapped around what you meant. And now today, you indeed have swapped around too, so the issue reported as `latest` is actually on `develop` and vice versa lol.

Okay, so `latest` is all good. Perfect as that was a core thing now fixed proper.
Now as for develop, I suspect that issue has ben there unreported for eons, so now to try and fix something on an alien OS - fun!

**Comment by JackDandy** [comment]
Ok i think i have fixed develop, can you let me know

**Comment by JackDandy** [comment]
Oops, did the `develop` fix, forgot to push, image now updated and ready for you to test.

**Comment by sanchon** [comment]
this is what i see in the container log: `/entrypoint.sh: line 13: groupmod: not found`

I don't know If there's any other log or info I can provide

**Comment by JackDandy** [comment]
nope that's fine. its tricky that we cannot verify the sha to make sure you have the correct image though

**Comment by JackDandy** [comment]
ah okay, you defo have not pulled the latest develop, try again

**Comment by sanchon** [comment]
tried again... deleted container and all images... it's the latest develop
sha256 means nothing, but it says Created 2021-09-26 11:33:26 and Size: 173.1Mb

**Comment by JackDandy** [comment]
another image pushed, fingers crossed

**Comment by sanchon** [comment]
this is what log says now:
```
usermod: no changes,
Already up to date.,
usermod: no changes,
Already up to date.,
usermod: no changes,
Already up to date.,
usermod: no changes,
```

**Comment by JackDandy** [comment]
looks fine, and can you access SickGear ?

**Comment by JackDandy** [comment]
I've tested and run all images fine.
