### ISSUE TITLE
Container failing startup

### ISSUE THREAD

**Issue by Androkiller** [SickGear/SickGear.Docker#46]
The latest version is failing to startup.

My startup command
`docker run -d \
        --name=sickgear2 \
        -p 8081:8081 \
        -e TZ=UTC \
        --restart unless-stopped \
        -v /data/videos/tvshows:/tvshows \
        -v /data/torrents/completed:/completed \
        -v /data/torrents/blackhole:/blackhole \
        -v /opt/sickgeardocker:/data \
        -e APP_UID=1007 \
        -e APP_GID=1001 \		
        sickgear/sickgear`

which produces the following error
`+--------------------------------------+
||      Official SickGear Docker      ||
||        Tracks branch:master        ||
+--------------------------------------+
Find third-party application helpers and
config files at; /data/autoProcessTV/
SABnzbd sample config file;
$ cp ./autoProcessTV.cfg.sample ./autoProcessTV.cfg
Deluge or Transmission sample config file;
$ cp ./onTxComplete.sample.cfg ./onTxComplete.cfg
On download completed helpers;
+- NZBGet, ./SickGear-NG/SickGear-NG.py
+- SABnzbd, ./sabToSickGear.py
+- Torrent (*nix), ./onTxComplete.sh
+- Torrent (Win), ./onTxComplete.bat
+----------------------------------------+
file "/data/_DOCKER.txt"     
+----------------------------------------+
/entrypoint.sh: line 60: su-exec: not found`

noting from the startup script i removed the env variables for the user and group and volume mappings, this also fails but on line 41

**Comment by JackDandy** [comment]
I take it that you were up to date with the builds and so reverted the Alpine update.

Please let me know if that is okay for you

**Comment by Androkiller** [comment]
> I take it that you were up to date with the builds and so reverted the Alpine update.
> 
> Please let me know if that is okay for you

Correct I was on the latest build.

Can confirm that it is now launching and working again 😀
