### ISSUE TITLE
Missing module in recent LATEST

### ISSUE THREAD

**Issue by irobot73** [SickGear/SickGear.Docker#47]
Pulled latest, spun up container & noted the following in the log.  Container does not start

+--------------------------------------+
||      Official SickGear Docker      ||
||        Tracks branch:master        ||
+--------------------------------------+
Find third-party application helpers and
config files at; /data/autoProcessTV/
SABnzbd sample config file;
$ cp ./autoProcessTV.cfg.sample ./autoProcessTV.cfg
Deluge or Transmission sample config file;
$ cp ./onTxComplete.sample.cfg ./onTxComplete.cfg
On download completed helpers;
+- NZBGet, ./SickGear-NG/SickGear-NG.py
+- SABnzbd, ./sabToSickGear.py
+- Torrent (*nix), ./onTxComplete.sh
+- Torrent (Win), ./onTxComplete.bat
+----------------------------------------+
file "/data/_DOCKER.txt"     
+----------------------------------------+
Traceback (most recent call last):
  File "/opt/SickGear/sickgear.py", line 95, in <module>
    import sickbeard
  File "/opt/SickGear/sickbeard/__init__.py", line 41, in <module>
    from . import classes, db, helpers, image_cache, indexermapper, logger, metadata, naming, people_queue, providers, \
  File "/opt/SickGear/sickbeard/helpers.py", line 41, in <module>
    from . import db, logger, notifiers
  File "/opt/SickGear/sickbeard/notifiers/__init__.py", line 24, in <module>
    from . import emby, kodi, plex, xbmc, \
  File "/opt/SickGear/sickbeard/notifiers/growl.py", line 24, in <module>
    from lib.apprise.plugins.NotifyGrowl.gntp import notifier as growl_notifier
ModuleNotFoundError: No module named 'lib.apprise'

**Comment by JackDandy** [comment]
actually, not quite fixed, but will be soon
