### ISSUE TITLE
Missing module (lib.apprise.plugins.NotifyBase) after latest update

### ISSUE THREAD

**Issue by irobot73** [SickGear/SickGear.Docker#49]
Appears the issue is back.  Pulled LATEST last night & fails to start container:
<pre>
+--------------------------------------+
||      Official SickGear Docker      ||
||        Tracks branch:master        ||
+--------------------------------------+
Find third-party application helpers and
config files at; /data/autoProcessTV/
SABnzbd sample config file;
$ cp ./autoProcessTV.cfg.sample ./autoProcessTV.cfg
Deluge or Transmission sample config file;
$ cp ./onTxComplete.sample.cfg ./onTxComplete.cfg
On download completed helpers;
+- NZBGet, ./SickGear-NG/SickGear-NG.py
+- SABnzbd, ./sabToSickGear.py
+- Torrent (*nix), ./onTxComplete.sh
+- Torrent (Win), ./onTxComplete.bat
+----------------------------------------+
file "/data/_DOCKER.txt"     
+----------------------------------------+
Traceback (most recent call last):
  File "/opt/SickGear/sickgear.py", line 95, in <module>
    import sickbeard
  File "/opt/SickGear/sickbeard/__init__.py", line 41, in <module>
    from . import classes, db, helpers, image_cache, indexermapper, logger, metadata, naming, people_queue, providers, \
  File "/opt/SickGear/sickbeard/helpers.py", line 41, in <module>
    from . import db, logger, notifiers
  File "/opt/SickGear/sickbeard/notifiers/__init__.py", line 24, in <module>
    from . import emby, kodi, plex, xbmc, \
  File "/opt/SickGear/sickbeard/notifiers/growl.py", line 24, in <module>
    from lib.apprise.plugins.NotifyGrowl.gntp import notifier as growl_notifier
  File "/opt/SickGear/lib/apprise/__init__.py", line 47, in <module>
    from .plugins.NotifyBase import NotifyBase
ModuleNotFoundError: No module named 'lib.apprise.plugins.NotifyBase'
</pre>

**Comment by JackDandy** [comment]
Okay, rebuilding images.

**Comment by JackDandy** [comment]
Should be good now.

**Comment by irobot73** [comment]
Didn't note anything via Watchtower over-night.  Deleted the container, pulled & started.  Same error as reported.

**Comment by TimCorcoran** [comment]
Hi @JackDandy 

I'm getting this exact same error right now when I update to the latest image, so the problem is still persistent.

**Comment by JackDandy** [comment]
hmm, last pull 43 mins ago.

what digest are you on?

**Comment by irobot73** [comment]
![Screenshot from 2022-11-13 07-55-10](https://user-images.githubusercontent.com/7168597/201522708-9f098247-ff2d-4199-a998-1f0d7a6fa605.png)

**Comment by JackDandy** [comment]
can we verify the issue exists on either following sha256 digest ...

amd64 = `ed951c2ce190d1f2d7714e66307befd9e59a19f170f19cd962244f60a0461ec3`
arm64 = `334a59de885fb55520184ba4536f29dcf97203a5ed2345bf680b63346b187433`

**Comment by irobot73** [comment]
![Screenshot from 2022-11-13 08-03-57](https://user-images.githubusercontent.com/7168597/201523020-081577f1-ce9d-4a64-9fa1-81de1159fa09.png)

**Comment by JackDandy** [comment]
> ![Screenshot from 2022-11-13 08-03-57](https://user-images.githubusercontent.com/7168597/201523020-081577f1-ce9d-4a64-9fa1-81de1159fa09.png)

Right, so you are on the wrong image

**Comment by irobot73** [comment]
![Screenshot from 2022-11-13 08-08-37](https://user-images.githubusercontent.com/7168597/201523237-9050fa2a-1248-4464-b90e-9c5c909ee9f1.png)
![Screenshot from 2022-11-13 08-09-21](https://user-images.githubusercontent.com/7168597/201523252-d9f6288c-fa0c-4631-b678-741883909e39.png)

No love (even w/ diff. SHA1

**Comment by JackDandy** [comment]
<img src="https://i.vgy.me/QoMjXS.png">

**Comment by irobot73** [comment]
Might be an ongoing issue
https://github.com/docker/hub-feedback/issues/1925#issuecomment-565646445

Gonna try a thing/two...brb

**Comment by JackDandy** [comment]
@irobot73 thanks for the feedback, i deleted your post as it exposed this thread on that other issue
