### ISSUE TITLE
Issue with apprise on older docker image

### ISSUE THREAD

**Issue by JackDandy** [SickGear/SickGear.Docker#50]
Solution: update to new image

**Comment by irobot73** [comment]
I tried w/ the SHA only & even specifying the platform.  Note they both pull the '1ec3' image, but still won't start

![platform](https://user-images.githubusercontent.com/7168597/201526498-44fda8a0-4c6a-4274-b46d-e7d6f83d1994.png)
![sha1](https://user-images.githubusercontent.com/7168597/201526499-4af22151-1778-43aa-8b8d-bf39f6ad3d61.png)

**Comment by JackDandy** [comment]
this is a different error now, can you post all of the output of the `traceback`?

**Comment by irobot73** [comment]
Output of 'docker-compose up': 

Creating network "sickgear_default" with the default driver
Pulling sickgear (sickgear/sickgear:latest@sha256:ed951c2ce190d1f2d7714e66307befd9e59a19f170f19cd962244f60a0461ec3)...
docker.io/sickgear/sickgear@sha256:ed951c2ce190d1f2d7714e66307befd9e59a19f170f19cd962244f60a0461ec3: Pulling from sickgear/sickgear
a71ff8a5264a: Pull complete
17297f89a7da: Pull complete
fff2a1e1540b: Pull complete
Digest: sha256:ed951c2ce190d1f2d7714e66307befd9e59a19f170f19cd962244f60a0461ec3
Status: Downloaded newer image for sickgear/sickgear@sha256:ed951c2ce190d1f2d7714e66307befd9e59a19f170f19cd962244f60a0461ec3
Creating sickgear ... done
Attaching to sickgear
sickgear    | +--------------------------------------+
sickgear    | ||      Official SickGear Docker      ||
sickgear    | ||        Tracks branch:master        ||
sickgear    | +--------------------------------------+
sickgear    | Find third-party application helpers and
sickgear    | config files at; /data/autoProcessTV/
sickgear    | 
sickgear    | SABnzbd sample config file;
sickgear    | $ cp ./autoProcessTV.cfg.sample ./autoProcessTV.cfg
sickgear    | Deluge or Transmission sample config file;
sickgear    | $ cp ./onTxComplete.sample.cfg ./onTxComplete.cfg
sickgear    | 
sickgear    | On download completed helpers;
sickgear    | +- NZBGet, ./SickGear-NG/SickGear-NG.py
sickgear    | +- SABnzbd, ./sabToSickGear.py
sickgear    | +- Torrent (*nix), ./onTxComplete.sh
sickgear    | +- Torrent (Win), ./onTxComplete.bat
sickgear    | +----------------------------------------+
sickgear    | file "/data/_DOCKER.txt"     
sickgear    | +----------------------------------------+
sickgear    | Traceback (most recent call last):
sickgear    |   File "/opt/SickGear/sickgear.py", line 95, in <module>
sickgear    |     import sickbeard
sickgear    |   File "/opt/SickGear/sickbeard/__init__.py", line 41, in <module>
sickgear    |     from . import classes, db, helpers, image_cache, indexermapper, logger, metadata, naming, people_queue, providers, \
sickgear    |   File "/opt/SickGear/sickbeard/helpers.py", line 41, in <module>
sickgear    |     from . import db, logger, notifiers
sickgear    |   File "/opt/SickGear/sickbeard/notifiers/__init__.py", line 24, in <module>
sickgear    |     from . import emby, kodi, plex, xbmc, \
sickgear    |   File "/opt/SickGear/sickbeard/notifiers/growl.py", line 24, in <module>
sickgear    |     from lib.apprise.plugins.NotifyGrowl.gntp import notifier as growl_notifier
sickgear    |   File "/opt/SickGear/lib/apprise/__init__.py", line 47, in <module>
sickgear    |     from .plugins.NotifyBase import NotifyBase
sickgear    | ModuleNotFoundError: No module named 'lib.apprise.plugins.NotifyBase'

YML: 

![platform](https://user-images.githubusercontent.com/7168597/201526786-0aa8794e-408c-4699-8bb0-d9b37eba0b3f.png)
![sha1](https://user-images.githubusercontent.com/7168597/201526787-2427395e-240a-463f-8c23-2cb60e7da8e6.png)

**Comment by irobot73** [comment]
Can you re-OPEN...or shall I create another/new ISSUE?

**Comment by JackDandy** [comment]
No need to reopen or new issue. Anything on this will be posted here

**Comment by JackDandy** [comment]
`latest` build with output of directory apprise...

<img src="https://i.vgy.me/VSicsf.png">

**Comment by irobot73** [comment]
Same error if using ':LATEST' or 
image: sickgear/sickgear:latest@sha256:32d96732ae7ea2b5ff295273fa1d9813cba397a0fd6d7bcbb2b45a019fe0a93e

![Screenshot from 2022-11-13 11-37-05](https://user-images.githubusercontent.com/7168597/201533062-fec387cc-3e2c-41f6-9163-cc7061684cd4.png)

**Comment by irobot73** [comment]
For giggles, can you add the same 'output of directory apprise' into the '_DOCKER.txt' file?  Get a 'pre' vs. 'post' we can compare (still learning Docker else I could console/bash in & give a LS -L myself )

**Comment by irobot73** [comment]
Doh, was using bash instead of sh to get into the container *facepalm*.  Maybe this helps?

```
/ # find / -name "apprise"
/opt/SickGear/apprise
/opt/SickGear/lib/apprise
/ # find / -name "NotifyBase"
/ # cd /opt/SickGear/lib/apprise/
/opt/SickGear/lib/apprise # ls -l
total 144
-rw-rw-r--    1 root     root         20448 Oct 31 23:11 Apprise.py
-rw-rw-r--    1 root     root          8403 Oct 31 23:11 AppriseAsset.py
-rw-rw-r--    1 root     root          9814 Oct 31 23:11 AppriseAttachment.py
-rw-rw-r--    1 root     root         13090 Oct 31 23:11 AppriseConfig.py
-rw-rw-r--    1 root     root          7036 Oct 31 23:11 AppriseLocale.py
-rw-rw-r--    1 root     root         18077 Oct 31 23:11 URLBase.py
-rw-rw-r--    1 root     root          2670 Oct 31 23:11 __init__.py
drwxrwxr-x    3 root     root          4096 Nov 13 16:16 assets
drwxrwxr-x    2 root     root          4096 Nov 13 16:16 attachment
-rw-rw-r--    1 root     root          3724 Oct 31 23:11 common.py
drwxrwxr-x    2 root     root          4096 Nov 13 16:16 config
drwxrwxr-x    3 root     root          4096 Nov 13 16:16 i18n
-rw-rw-r--    1 root     root          2259 Oct 31 23:11 logger.py
drwxrwxr-x    2 root     root          4096 Nov 13 16:16 plugins
-rw-rw-r--    1 root     root         22196 Oct 31 23:11 utils.py
/opt/SickGear/lib/apprise # cd plugins/
/opt/SickGear/lib/apprise/plugins # ls -l
total 0
/opt/SickGear/lib/apprise/plugins # cd /opt/SickGear/apprise/plugins/
/opt/SickGear/apprise/plugins # ls -l
total 72
-rw-rw-r--    1 root     root         15503 Oct 31 23:11 NotifyBase.py
-rw-rw-r--    1 root     root         27533 Oct 31 23:11 NotifyEmail.py
drwxrwxr-x    3 root     root          4096 Nov 13 16:16 NotifyGrowl
drwxrwxr-x    2 root     root          4096 Nov 13 16:16 NotifyXMPP
-rw-rw-r--    1 root     root         17519 Oct 31 23:11 __init__.py
/opt/SickGear/apprise/plugins # 
```

**Comment by JackDandy** [comment]
hmm strange, but yeah, that does help :)

**Comment by JackDandy** [comment]
try this...
`13e79b1871ff022c533248dfe8ccf5b9b85de679d97ec72a0107862937989ef2 `

**Comment by JackDandy** [comment]
```
/ # find / -name "apprise"
/opt/SickGear/apprise
/opt/SickGear/lib/apprise
```
That was most useful :)

**Comment by irobot73** [comment]
Tried w/ LATEST (nothing else) & pulled properly this time!!

Took some time to give me the 'STARTING msg, but came up after some nail-biting :)

![Screenshot from 2022-11-13 14-42-53](https://user-images.githubusercontent.com/7168597/201541060-36126659-d282-44dc-88d2-d95c8e064420.png)

**Comment by JackDandy** [comment]
> Took some time to give me the 'STARTING msg

Would you say longer than normal, are you accustomed to the startup time?

**Comment by irobot73** [comment]
Def. longer than before, I was afraid it was hung.

Now, restarting the container did respond as I'd expect it.

Since Watchtower is set to update @ 1AM, I'm not too worried about the initial container start-up (vs. restart) {wink}  I mean, it was down for a few days & I have other containers running, might have just been a "me" thing {shrug}

Willing to help w/ any (major) revisions if you wish to reach out. Did seem like a lot of back/forth w/ the code base.

**Comment by JackDandy** [comment]
Yeah, the image build was changed because it was stuck on an older Alpine due to a compatibility issue, it's now the very latest edge, therefore most things in the image are at the latest versions too, which was important for a major vulnerability fix to get baked in. During this, a goal to reduce the larger image size came about, and in that cleanup, the Apprise issue was created by user error.

There will be other builds, but the structure is now stable.

So, thanks for your help.

**Comment by irobot73** [comment]
Glad to be of service (learned a few things along the way :star: )
