### ISSUE TITLE
Container failing to start

### ISSUE THREAD

**Issue by Androkiller** [SickGear/SickGear.Docker#51]
Got an issue with the container starting on both latest and develop branches getting the following error when looking at the logs _exec /entrypoint.sh: exec format error_

**Comment by JackDandy** [comment]
is that for RPi?

**Comment by Androkiller** [comment]
> is that for RPi?

Nope running on amd64 ubuntu 22.04 lts

**Comment by TimCorcoran** [comment]
This is likely a similar issue to the one reported under issue #49, which you deleted.
After my failed attempt at updating yesterday, I rolled back. I have just attempted to update again today and am seeing this same error that @Androkiller reports;

# docker logs --tail 50 --follow --timestamps docker_sickgear_1
2022-11-14T10:41:33.659089344Z exec /entrypoint.sh: exec format error
2022-11-14T10:41:35.803246812Z exec /entrypoint.sh: exec format error
2022-11-14T10:41:36.806145149Z exec /entrypoint.sh: exec format error
2022-11-14T10:41:38.027943855Z exec /entrypoint.sh: exec format error
2022-11-14T10:41:39.691767653Z exec /entrypoint.sh: exec format error
2022-11-14T10:41:42.097058790Z exec /entrypoint.sh: exec format error
2022-11-14T10:41:46.120262372Z exec /entrypoint.sh: exec format error
2022-11-14T10:41:53.674695437Z exec /entrypoint.sh: exec format error
2022-11-14T10:42:07.391672235Z exec /entrypoint.sh: exec format error
2022-11-14T10:42:33.743312334Z exec /entrypoint.sh: exec format error
2022-11-14T10:43:25.737558922Z exec /entrypoint.sh: exec format error
2022-11-14T10:44:26.514551774Z exec /entrypoint.sh: exec format error
2022-11-14T10:45:27.303280202Z exec /entrypoint.sh: exec format error

I have updated to the latest image, which is being shipped with the following digest;
# docker images --digests | grep sickgear
sickgear/sickgear                      latest    sha256:25820e0dfc4dceb333dbf114a2cab964c5438def5e513a5c41f3ba0cdbff7042   ee5004fa7852   10 hours ago    97.3MB

**Comment by JackDandy** [comment]
Yup. issue #49 deleted because the container was reported working.

Can either of you connect to the docker (`-i`) and do `find / -name entrypoint.sh`

**Comment by JackDandy** [comment]
btw there is an outstanding issue where the docker hub does **not** report the correct manifest hash, the one that I posted above.

**Comment by Androkiller** [comment]
noted i was not running develop build did just pull the image but forgot to mention to use it in the run command.
So develop build gives a different error _/entrypoint.sh: line 14: groupmod: not found_ which makes sense due to i am now seeing files being created with incorrect user in the mounted volumes.(creating as root) sha256:b876efe2e486e930db109e5087f76b28db9b7410089b063089e50bb19489acb8 also reports _Docker on linux, amd64_

latest sha256:ee5004fa7852ced4654f4ae6322ad623f19d779ee9141306ca42a036e15cfa5f reports _Docker on linux, ppc64le_. this different to latest unsure if intentional. 

i dont following your suggestion of connecting to docker, if your suggesting connecting the container its not possible due to the container will not start.

**Comment by irobot73** [comment]
LATEST: 'sickgear    | exec /entrypoint.sh: exec format error'

DEVELOP:  'sickgear    | /entrypoint.sh: line 14: groupmod: not found'

Both match the SHA on the HUB

![Screenshot from 2022-11-14 07-22-50](https://user-images.githubusercontent.com/7168597/201659201-41a9b843-f970-44bc-9a23-2d44373763f1.png)

**Comment by JackDandy** [comment]
develop pushed - fingers crossed

**Comment by irobot73** [comment]
Newest DEVELOP gives same error:  'sickgear    | /entrypoint.sh: line 14: groupmod: not found'
![Screenshot from 2022-11-14 07-48-26](https://user-images.githubusercontent.com/7168597/201664315-02fe8a1f-73ab-48ab-8e0f-844c312d77c4.png)

**Comment by irobot73** [comment]
The latest  LATEST seems to be working again (& this start-up ['...Starting SickGear...'] was almost immediate)

![Screenshot from 2022-11-14 07-48-26](https://user-images.githubusercontent.com/7168597/201668066-1e91c0ac-c9c8-46c3-91e6-90b5fa40c1eb.png)

**Comment by irobot73** [comment]
Tell whomever to stop playing on the BUILD server :smile:

**Comment by TimCorcoran** [comment]
I can confirm that it's now working for me, although I'm getting digest sha256:ad42fdf222a6b8f91e95674c6512f6688274a376a7c9850e59ab429cd7adaef7

**Comment by irobot73** [comment]
Thinking Docker has some issue(s) recently.  Kinda hit/miss using just
     sickgear/sickgear:latest

And I don't want to pigeon-hole/update for EVERY update myself
     sickgear/sickgear:latest@sha256:519f0b15293dfa0189f3cd97a04573400ad7e0314d10e3fb1f380df7a0625a88

**Comment by JackDandy** [comment]
> Tell whomever to stop playing on the BUILD server 😄

cheeky, as soon as it is stable again. to be fair. there have been no changes to "latest" apart from trying to get the build server to parallel build instead of one at a time. Good news, it reduces overall build time, from like 15mins to a few mins, problem is, each build is then individually sent to docker hub, and the hub will only list the most recent push.

**Comment by irobot73** [comment]
Correct.  DEV still dorked

![Screenshot from 2022-11-14 09-18-16](https://user-images.githubusercontent.com/7168597/201683116-8e34fca8-9b9f-4661-978b-eca0dca73d54.png)

**Comment by Androkiller** [comment]
cant pull that version yet still gives me sha256:328e282dd11ed3a05bde140ff7a536262044de3877a669a6409399ae52e44685 as latest for develop

**Comment by JackDandy** [comment]
> 328e282dd11ed3a05bde140ff7a536262044de3877a669a6409399ae52e44685

that maybe the wrong value, can you try to start it up and see if it works

**Comment by Androkiller** [comment]
ye portainer is showing the digest wrong as the image layers are correct after i double checked

**Comment by JackDandy** [comment]
yeah, @irobot73 and I had much fund yesterday with things not displaying correct sha's

**Comment by irobot73** [comment]
DEVELOP appears to be working now

![Screenshot from 2022-11-14 11-36-35](https://user-images.githubusercontent.com/7168597/201715166-1d1937d8-e17b-4e3c-bd0c-6d67b81c11e1.png)

**Comment by JackDandy** [comment]
great!
